/* Generated by re2c 0.13.5 on Mon May 19 14:12:10 2014 */
#line 3 "./ISO8601/NJISO8601Parser.h"

enum NJISO8601Condition {
    kNJISO8601ConditionStart,
    kNJISO8601ConditionDateBegin,
    kNJISO8601ConditionDateEnd,
    kNJISO8601ConditionTimeBegin,
    kNJISO8601ConditionTimeEnd,
    kNJISO8601ConditionTimeZoneBegin,
    kNJISO8601ConditionTimeZoneEnd,
    kNJISO8601ConditionDurationBegin,
    kNJISO8601ConditionRecurringIntervalBegin,
};
